### ISSUE TITLE
ZSH update version error.

### ISSUE THREAD

**Issue by Aisuko** [G-Club/zshconfig#22]
```
[Oh My Zsh] Would you like to update? [Y/n]: y
Updating Oh My Zsh
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Total 110 (delta 41), reused 41 (delta 41), pack-reused 69
Receiving objects: 100% (110/110), 46.55 KiB | 7.00 KiB/s, done.
Resolving deltas: 100% (56/56), completed with 23 local objects.
From https://github.com/ohmyzsh/ohmyzsh
 * branch              master     -> FETCH_HEAD
   64a7f6b3..17428f3c  master     -> origin/master
 .github/ISSUE_TEMPLATE/bug_report.md                   | 32 +++++++++++++++-----------------
 .github/ISSUE_TEMPLATE/feature_request.md              | 10 +++++-----
 .github/ISSUE_TEMPLATE/support.md                      |  2 --
 .github/PULL_REQUEST_TEMPLATE.md                       | 17 +++++++++++++++++
 .github/workflows/{check-suite.yml => main.yml}        |  2 +-
 README.md                                              |  2 +-
 lib/completion.zsh                                     |  3 +++
 lib/git.zsh                                            |  9 +++++++++
 plugins/aws/aws.plugin.zsh                             |  3 ++-
 plugins/common-aliases/common-aliases.plugin.zsh       |  1 +
 plugins/dotnet/README.md                               | 20 +++++++++++---------
 plugins/dotnet/dotnet.plugin.zsh                       |  2 ++
 plugins/jump/README.md                                 | 12 ++++++++++++
 plugins/jump/jump.plugin.zsh                           | 31 +++++++++++++------------------
 plugins/kube-ps1/README.md                             |  2 ++
 plugins/lol/README.md                                  |  4 ++--
 plugins/systemadmin/systemadmin.plugin.zsh             |  4 ++--
 plugins/systemd/systemd.plugin.zsh                     | 65 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------
 plugins/vagrant/_vagrant                               |  4 ++--
 plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh | 64 +++++++++++++++++++---------------------------------------------
 plugins/vscode/README.md                               | 12 +++++++-----
 plugins/vscode/vscode.plugin.zsh                       | 14 +++++++++++---
 themes/af-magic.zsh-theme                              |  4 ++--
 themes/candy-kingdom.zsh-theme                         | 24 +++++++++++++-----------
 themes/kiwi.zsh-theme                                  |  4 +---
 25 files changed, 212 insertions(+), 135 deletions(-)
 create mode 100644 .github/PULL_REQUEST_TEMPLATE.md
 rename .github/workflows/{check-suite.yml => main.yml} (97%)
First, rewinding head to replay your work on top of it...
Applying: update
Using index info to reconstruct a base tree...
M       lib/completion.zsh
Falling back to patching base and 3-way merge...
Auto-merging lib/completion.zsh
CONFLICT (content): Merge conflict in lib/completion.zsh
Removing custom/plugins/example/example.plugin.zsh
error: Failed to merge in the changes.
Patch failed at 0001 update
hint: Use 'git am --show-current-patch' to see the failed patch
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
There was an error updating. Try again later?
/Users/noctisli/.oh-my-zsh/lib/completion.zsh:75: parse error near `<<<'

```

**Comment by Aisuko** [comment]
@spring-bu Did we make a change on the file which was conflict?

**Comment by Heresh83** [comment]
> ```
> [Oh My Zsh] Would you like to update? [Y/n]: y
> Updating Oh My Zsh
> remote: Enumerating objects: 41, done.
> remote: Counting objects: 100% (41/41), done.
> remote: Total 110 (delta 41), reused 41 (delta 41), pack-reused 69
> Receiving objects: 100% (110/110), 46.55 KiB | 7.00 KiB/s, done.
> Resolving deltas: 100% (56/56), completed with 23 local objects.
> From https://github.com/ohmyzsh/ohmyzsh
>  * branch              master     -> FETCH_HEAD
>    64a7f6b3..17428f3c  master     -> origin/master
>  .github/ISSUE_TEMPLATE/bug_report.md                   | 32 +++++++++++++++-----------------
>  .github/ISSUE_TEMPLATE/feature_request.md              | 10 +++++-----
>  .github/ISSUE_TEMPLATE/support.md                      |  2 --
>  .github/PULL_REQUEST_TEMPLATE.md                       | 17 +++++++++++++++++
>  .github/workflows/{check-suite.yml => main.yml}        |  2 +-
>  README.md                                              |  2 +-
>  lib/completion.zsh                                     |  3 +++
>  lib/git.zsh                                            |  9 +++++++++
>  plugins/aws/aws.plugin.zsh                             |  3 ++-
>  plugins/common-aliases/common-aliases.plugin.zsh       |  1 +
>  plugins/dotnet/README.md                               | 20 +++++++++++---------
>  plugins/dotnet/dotnet.plugin.zsh                       |  2 ++
>  plugins/jump/README.md                                 | 12 ++++++++++++
>  plugins/jump/jump.plugin.zsh                           | 31 +++++++++++++------------------
>  plugins/kube-ps1/README.md                             |  2 ++
>  plugins/lol/README.md                                  |  4 ++--
>  plugins/systemadmin/systemadmin.plugin.zsh             |  4 ++--
>  plugins/systemd/systemd.plugin.zsh                     | 65 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------
>  plugins/vagrant/_vagrant                               |  4 ++--
>  plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh | 64 +++++++++++++++++++---------------------------------------------
>  plugins/vscode/README.md                               | 12 +++++++-----
>  plugins/vscode/vscode.plugin.zsh                       | 14 +++++++++++---
>  themes/af-magic.zsh-theme                              |  4 ++--
>  themes/candy-kingdom.zsh-theme                         | 24 +++++++++++++-----------
>  themes/kiwi.zsh-theme                                  |  4 +---
>  25 files changed, 212 insertions(+), 135 deletions(-)
>  create mode 100644 .github/PULL_REQUEST_TEMPLATE.md
>  rename .github/workflows/{check-suite.yml => main.yml} (97%)
> First, rewinding head to replay your work on top of it...
> Applying: update
> Using index info to reconstruct a base tree...
> M       lib/completion.zsh
> Falling back to patching base and 3-way merge...
> Auto-merging lib/completion.zsh
> CONFLICT (content): Merge conflict in lib/completion.zsh
> Removing custom/plugins/example/example.plugin.zsh
> error: Failed to merge in the changes.
> Patch failed at 0001 update
> hint: Use 'git am --show-current-patch' to see the failed patch
> Resolve all conflicts manually, mark them as resolved with
> "git add/rm <conflicted_files>", then run "git rebase --continue".
> You can instead skip this commit: run "git rebase --skip".
> To abort and get back to the state before "git rebase", run "git rebase --abort".
> There was an error updating. Try again later?
> /Users/noctisli/.oh-my-zsh/lib/completion.zsh:75: parse error near `<<<'
> ```

[https://github.com/G-Club/zshconfig/issues/22#issue-563937343]() ``

**Comment by Heresh83** [comment]
> > ```
> > [Oh My Zsh] Would you like to update? [Y/n]: y
> > Updating Oh My Zsh
> > remote: Enumerating objects: 41, done.
> > remote: Counting objects: 100% (41/41), done.
> > remote: Total 110 (delta 41), reused 41 (delta 41), pack-reused 69
> > Receiving objects: 100% (110/110), 46.55 KiB | 7.00 KiB/s, done.
> > Resolving deltas: 100% (56/56), completed with 23 local objects.
> > From https://github.com/ohmyzsh/ohmyzsh
> >  * branch              master     -> FETCH_HEAD
> >    64a7f6b3..17428f3c  master     -> origin/master
> >  .github/ISSUE_TEMPLATE/bug_report.md                   | 32 +++++++++++++++-----------------
> >  .github/ISSUE_TEMPLATE/feature_request.md              | 10 +++++-----
> >  .github/ISSUE_TEMPLATE/support.md                      |  2 --
> >  .github/PULL_REQUEST_TEMPLATE.md                       | 17 +++++++++++++++++
> >  .github/workflows/{check-suite.yml => main.yml}        |  2 +-
> >  README.md                                              |  2 +-
> >  lib/completion.zsh                                     |  3 +++
> >  lib/git.zsh                                            |  9 +++++++++
> >  plugins/aws/aws.plugin.zsh                             |  3 ++-
> >  plugins/common-aliases/common-aliases.plugin.zsh       |  1 +
> >  plugins/dotnet/README.md                               | 20 +++++++++++---------
> >  plugins/dotnet/dotnet.plugin.zsh                       |  2 ++
> >  plugins/jump/README.md                                 | 12 ++++++++++++
> >  plugins/jump/jump.plugin.zsh                           | 31 +++++++++++++------------------
> >  plugins/kube-ps1/README.md                             |  2 ++
> >  plugins/lol/README.md                                  |  4 ++--
> >  plugins/systemadmin/systemadmin.plugin.zsh             |  4 ++--
> >  plugins/systemd/systemd.plugin.zsh                     | 65 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------
> >  plugins/vagrant/_vagrant                               |  4 ++--
> >  plugins/virtualenvwrapper/virtualenvwrapper.plugin.zsh | 64 +++++++++++++++++++---------------------------------------------
> >  plugins/vscode/README.md                               | 12 +++++++-----
> >  plugins/vscode/vscode.plugin.zsh                       | 14 +++++++++++---
> >  themes/af-magic.zsh-theme                              |  4 ++--
> >  themes/candy-kingdom.zsh-theme                         | 24 +++++++++++++-----------
> >  themes/kiwi.zsh-theme                                  |  4 +---
> >  25 files changed, 212 insertions(+), 135 deletions(-)
> >  create mode 100644 .github/PULL_REQUEST_TEMPLATE.md
> >  rename .github/workflows/{check-suite.yml => main.yml} (97%)
> > First, rewinding head to replay your work on top of it...
> > Applying: update
> > Using index info to reconstruct a base tree...
> > M       lib/completion.zsh
> > Falling back to patching base and 3-way merge...
> > Auto-merging lib/completion.zsh
> > CONFLICT (content): Merge conflict in lib/completion.zsh
> > Removing custom/plugins/example/example.plugin.zsh
> > error: Failed to merge in the changes.
> > Patch failed at 0001 update
> > hint: Use 'git am --show-current-patch' to see the failed patch
> > Resolve all conflicts manually, mark them as resolved with
> > "git add/rm <conflicted_files>", then run "git rebase --continue".
> > You can instead skip this commit: run "git rebase --skip".
> > To abort and get back to the state before "git rebase", run "git rebase --abort".
> > There was an error updating. Try again later?
> > /Users/noctisli/.oh-my-zsh/lib/completion.zsh:75: parse error near `<<<'
> > ```
> 
> https://github.com/G-Club/zshconfig/issues/22#issue-563937343 ''
